language: node_js
sudo: required
node_js:
  - "6.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  #- npm i npm@2.14.4 --global
  - sudo apt-get  update
  - sudo apt-get install -y libavahi-compat-libdnssd-dev
  - sudo add-apt-repository -y ppa:chris-lea/zeromq
  - sudo apt-get install -y libzmq3-dbg libzmq3-dev libzmq3
  - npm i -g typescript
  - tsc
