language: node_js
node_js:
  - "0.11"
before_install:
  - "curl http://download.zeromq.org/zeromq-4.0.4.tar.gz > zeromq.tar.gz; tar -zxvf zeromq.tar.gz; cd zeromq-4.0.4; ./configure;make;make install"
